name: 'Terraform'

on:
  push:
    branches:
    - nys-deploy-test
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=nys-cpt-dev-terraform-state" -backend-config="key=dev-terraform-state" -backend-config="profile=default"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -var-file=env-vars/nys-dev.tfvars -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/nys-deploy-test' && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file=env-vars/nys-dev.tfvars -input=false

