name: 'Terraform'

on:
  push:
    branches:
    - nys-deploy-test
    - nys-qa
    - nys-prod
    - nys
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Select Target Environment
      run: |
        export ENV_REF=${GITHUB_REF#refs/heads/}
        case "$ENV_REF" in
        nys-deploy-test|nys)
          ENV_REF="nys-dev" ;;
        esac
        echo "##[set-env name=deployment_environment;]$ENV_REF"

    - name: Terraform Init
      run: terraform init -backend-config="bucket=nys-cpt-dev-terraform-state" -backend-config="key=dev-terraform-state" -backend-config="profile=default"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -var-file=env-vars/${deployment_environment}.tfvars -input=false

    - name: Terraform Apply
      if: startsWith(github.ref, 'nys') && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file=env-vars/${deployment_environment}.tfvars -input=false

